<a href="https://colab.research.google.com/github/scottspurlock/csc4422-s2026/blob/main/projects/project2_starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CSC 4422 DMML
## Project 2: Machine Learning

This notebook shows how to create an entry for the Project 2 Kaggle competition: https://www.kaggle.com/t/2db3cb64e7fe459f80e0c2a4c07ace27

- Public data: https://drive.google.com/uc?export=download&id=1pRAvxdUr9SU9H5puLK7xBg256sWCO9VE

- Competition data:
https://drive.google.com/uc?export=download&id=1WVKCy9bbqZjHpZ0cjaPm7_4m4LoRobmd

In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

## Read in the public data

In [2]:
public_url = 'https://drive.google.com/uc?export=download&id=1pRAvxdUr9SU9H5puLK7xBg256sWCO9VE'

df = pd.read_csv(public_url)
df.head()

,customer_id,name_title,registration_date,zip_code,education_level,monthly_income_reported,est_annual_spend,devices_active,login_hours_month_1,login_hours_month_2,internal_metric_alpha,internal_metric_beta,target_upgrade
0,100000,Kenneth Cunningham - Server,2022-04-06,73301,Associate,4261.21,11638.373759,Desktop,31.1,43.7,78.148,62.443,0
1,100001,Augustine Cummings - Server,2022-04-07,60601,Associate,4849.35,13884.185975,Desktop,24.1,23.6,34.912,107.925,0
2,100002,Dennis Lee - Server,2021-12-26,44114,High School,3532.19,12509.558322,Mobile,10.3,0.9,6.159,54.027,0
3,100003,Adam Smith - Server,2022-06-25,73301,Associate,8957.24,14000.488342,"Mobile,Desktop",20.3,31.4,86.928,33.977,0
4,100004,Sherry Mclure - Server,2022-06-11,73301,Bachelors,5438.78,19557.292989,"Mobile,Desktop",6.6,0.0,77.235,61.218,0

## Read in the competition data
Note that while the public data includes the target, target_upgrade, the competition data doesn't, since the goal of the competition is to predict this.

In [3]:
competition_url = 'https://drive.google.com/uc?export=download&id=1WVKCy9bbqZjHpZ0cjaPm7_4m4LoRobmd'

df_competition = pd.read_csv(competition_url)
df_competition.head()

,customer_id,name_title,registration_date,zip_code,education_level,monthly_income_reported,est_annual_spend,devices_active,login_hours_month_1,login_hours_month_2,internal_metric_alpha,internal_metric_beta
0,200000,Berna Flannery - Trucker,2021-05-20,90210,Bachelors,11209.79,24404.113466,"Mobile,Desktop",18.6,17.2,16.219,53.461
1,200001,Erin Lobel - Sales Associate,2022-05-23,73301,Bachelors,4293 dollars,12852.663044,"Mobile,Desktop",22.3,30.0,80.963,54.747
2,200002,Shelia Strickler - Clerk,2022-05-01,90210,Bachelors,8404.83,20064.261994,Mobile,15.2,21.5,61.735,40.575
3,200003,Patricia Wilkerson - Server,2021-11-10,60601,High School,2879.48,7675.675695,Desktop,26.0,31.8,26.444,86.132
4,200004,Edward Bush - Sales Associate,2022-08-12,44114,Bachelors,5783.6,7911.106239,Mobile,26.1,33.5,63.084,43.783

## Next would be EDA and data wrangling
For simplicity, I'll just select a few numeric columns that are already ok for making a model. You'll want to do more to wrangle the data into shape.

In [4]:
X = df[['zip_code', 'est_annual_spend', 'internal_metric_alpha']]
y = df['target_upgrade']

X.head()

   zip_code  est_annual_spend  internal_metric_alpha
0     73301      11638.373759                 78.148
1     60601      13884.185975                 34.912
2     44114      12509.558322                  6.159
3     73301      14000.488342                 86.928
4     73301      19557.292989                 77.235

## Next we would want to perform experiments with the public data to find the best type of model and best hyperparameters
For simplicity, I'm just going to train a basic KNN model without experimenting.

For this project, we care most about the average f1 score, which you can calculate using f1_score, as shown below, or find it in the more general classification_report.

In [5]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=1)

model = KNeighborsClassifier(n_neighbors=1)
model.fit(Xtrain, ytrain)
ypred = model.predict(Xtest)

acc = accuracy_score(ytest, ypred)
f1 = f1_score(ytest, ypred, average='macro')
print(f'Our model has accuracy {acc:.2f} and f1 score {f1:.2f}')

print()

print(classification_report(ytest, ypred))

Our model has accuracy 0.67 and f1 score 0.49

              precision    recall  f1-score   support

           0       0.78      0.80      0.79      1574
           1       0.20      0.18      0.19       426

    accuracy                           0.67      2000
   macro avg       0.49      0.49      0.49      2000
weighted avg       0.66      0.67      0.66      2000

## Now use your trained model to predict the competition data
Make sure to do the same things to the competition data as you do to the public data

Notes:
- use the same columns for the competition data that the trained model is expecting.
- if you cleaned (or normalized, etc.) a column in the public data, clean the column in the competition data in the same way.
- don't drop any of the rows in the competition data, since you need to make predictions for all the rows.
- we don't have target_upgrade for the competition data, so we can't evaluate how well the model works on it here. Instead we'll upload the predictions to the competition site, which does have the target_upgrade, and will tell us the f1 score.

In [6]:
Xcompetition = df_competition[['zip_code', 'est_annual_spend', 'internal_metric_alpha']]
Xcompetition.head()

   zip_code  est_annual_spend  internal_metric_alpha
0     90210      24404.113466                 16.219
1     73301      12852.663044                 80.963
2     90210      20064.261994                 61.735
3     60601       7675.675695                 26.444
4     44114       7911.106239                 63.084

## Once the final model is trained, we can predict the competition data

In [7]:
ypred = model.predict(Xcompetition)
print('First 10 predictions:', ypred[:10])

First 10 predictions: [0 1 0 0 0 0 1 1 1 0]

## For submission to the Kaggle competition, we need to create a csv file
The format will have a column for customer_id and one for the predictions, and one row for each competition example.

### Notes
- Kaggle is expecting 2000 predictions. Make sure not to drop any of the rows from the competition data.
- Kaggle is expecting predictions to be 0's or 1's
- Kaggle needs the customer_id's to match up predictions with the right answers, so we'll use the customer_id's from the competition dataframe.

In [8]:
ids = df_competition['customer_id']
predictions = ypred

# make a dataframe to hold the competition entry
output = pd.DataFrame({'customer_id': ids, 'target_upgrade': predictions})

output

      customer_id  target_upgrade
0          200000               0
1          200001               1
2          200002               0
3          200003               0
4          200004               0
...           ...             ...
1995       201995               0
1996       201996               1
1997       201997               1
1998       201998               0
1999       201999               0

[2000 rows x 2 columns]

Save the predictions as a CSV file

In [9]:
output.to_csv('submission.csv', index=False)
print("Kaggle submission was successfully saved...")

Kaggle submission was successfully saved...

Click on the file folder at the far left of the screen in Google Colab to see the files saved in your Colab storage. Download the file submission.csv to your computer. Then upload it to the Kaggle competition by clicking on "submit predictions" on the contest page: https://www.kaggle.com/t/2db3cb64e7fe459f80e0c2a4c07ace27

After submission, Kaggle will score your predictions against the hidden correct values for the target column using f1 score. When I submitted this set of predictions, I got a score of 0.51, so there's plenty of room for improvement!